version: "2.13"
services:
  grafana:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    container_name: custom_grafana

volumes:
  grafana-storage: